### ISSUE TITLE
Adding description to questions

### ISSUE THREAD

**Issue by deveshks** [varunu28/LeetCode-Java-Solutions#1]
Is it possible to add the description to the questions you have added in the repository, especially for the Premium ones which are generally locked for free users?
I can open a Pull Request in adding description to non-Premium ones to help the cause.

**Comment by varunu28** [comment]
@deveshks I think the Leetcode premium subscription is worth it and I don't feel that it is a good idea to convert this repository to an unofficial copy of Leetcode question. Anyone preparing for interviews can invest in a premium subscription as the returns are n folds. 

Still, there are websites such as Laicode and Interviewbit which have free access to multiple Leetcode premium questions.
